// Generated by https://quicktype.io
// import 'package:teslo_shop/features/auth/domain/domain.dart';
import 'package:teslo_shop/features/shared/infrastructure/inputs/inputs.dart';
// import 'package:teslo_shop/features/shared/infrastructure/inputs/lastperioddate.dart';
// import 'package:teslo_shop/features/shared/infrastructure/inputs/medicalstaffemail.dart';
import 'package:teslo_shop/features/shared/shared.dart';

class Patient {
  FirstName firstName;
  LastName lastName;
  BornDate? bornDate;
  DueDate dueDate;
  Email email;
  Height height;
  List<String> images;
  List<Map<String, dynamic>> medicalStaff;
  Phone phone;
  String comuneLiving;
  Rut rut;
  LastPeriodDate lastPeriodDate;
  int pregnancyWeek;
  int pregnancyWeekDay;
  String subscriptionDate;
  String planType;
  String healthInsurance;
  String? babyName;
  FirstName partnerFirstName;
  LastName partnerLastName;
  PartnerPhone partnerPhone;
  String? gestationalAge;
  bool babyIsBorn;
  String category;
  String? region;
  String? province;
  String? address;
  String? midwife;
  String? group;
  MedicalStaffEmail medicalStaffEmail;


  Patient({
    required this.firstName,
    required this.lastName,
    this.bornDate,
    required this.dueDate,
    required this.email,
    required this.height,
    required this.images,
    required this.medicalStaff,
    required this.phone,
    required this.comuneLiving,
    required this.rut,
    required this.lastPeriodDate,
    required this.pregnancyWeek,
    required this.pregnancyWeekDay,
    required this.subscriptionDate,
    required this.planType,
    required this.healthInsurance,
    this.babyName,
    required this.partnerFirstName,
    required this.partnerLastName,
    required this.partnerPhone,
    this.gestationalAge,
    required this.babyIsBorn,
    required this.category,
    required this.region,
    required this.province,
    required this.address, 
    required this.midwife, 
    required this.group,
    required this.medicalStaffEmail,

  });
}

// // Generated by https://quicktype.io
// import 'package:teslo_shop/features/auth/domain/domain.dart';

// class Product {
//   String id;
//   String title;
//   double price;
//   String description;
//   String slug;
//   int stock;
//   List<String> sizes;
//   String gender;
//   List<String> tags;
//   List<String> images;
//   User? user;

//   Product({
//     required this.id,
//     required this.title,
//     required this.price,
//     required this.description,
//     required this.slug,
//     required this.stock,
//     required this.sizes,
//     required this.gender,
//     required this.tags,
//     required this.images,
//     this.user,
//   });
// }