name: teslo_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  auth0_flutter: ^1.7.0
  dio: ^5.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.7.0
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  open_file: ^3.3.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  platform: ^3.1.5
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
