// Generated by https://quicktype.io/

class HealthProvider {
  String firstName;
  String lastName;
  String rut;
  String email;
  String phone;
  String code;
  String national_registration_number;
  String occupation;
  String health_institution_1;
  String health_institution_2;
  String health_institution_3;
  String status;
  List<Map<String, dynamic>> patients;


  HealthProvider({
    required this.firstName,
    required this.lastName,
    required this.rut,
    required this.email,
    required this.phone,
    required this.code,
    required this.national_registration_number,
    required this.occupation,
    required this.health_institution_1,
    required this.health_institution_2,
    required this.health_institution_3,
    required this.status,
    required this.patients,
  });
}
